name: TestPlugin
main: de.dennisfricke.testplugin.TestPlugin
version: ${version}
commands:
  pos:
    description: Displays your position or teleports you to another.
    usage: "Usage: '/pos' to get current position, or '/pos x y z' to teleport to x,y,z"