name: TestPlugin
main: de.dennisfricke.testplugin.TestPlugin
version: 1.0.0
commands:
    skin-add:
        description: Add skin to selection menu.
        usage: "Usage: /skin-add [onlinePlayer] to add a skin to selection"
    skin-set:
        description: Set skin to certain player.
        usage: "Usage: /skin-set [offlinePlayer] [onlinePlayer]"